name: Update Crypto Prices
on:
  schedule:
    # Runs every hour (adjust the cron expression as needed)
    - cron: "0 * * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch and Update Crypto Prices
        run: |
          # Fetch current prices for BTC and ETH from CoinGecko
          PRICES=$(curl -s "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum&vs_currencies=usd")
          echo "DEBUG: API output: $PRICES"
          PRICE_BTC=$(echo "$PRICES" | jq -r '.bitcoin.usd')
          PRICE_ETH=$(echo "$PRICES" | jq -r '.ethereum.usd')
          echo "DEBUG: BTC: $PRICE_BTC, ETH: $PRICE_ETH"
  
          # Use Perl with a non-greedy regex to update the multiline block in README.md
          perl -0777 -pi -e "s|<!-- CRYPTO_TICKER_START -->.*?<!-- CRYPTO_TICKER_END -->|<!-- CRYPTO_TICKER_START -->\n**BTC:** \$${PRICE_BTC} **ETH:** \$${PRICE_ETH}\n<!-- CRYPTO_TICKER_END -->|s" README.md
          
          echo "DEBUG: Updated README content:"
          cat README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update crypto prices" || echo "No changes to commit"
          git push
