name: Update Crypto Prices

on:
  schedule:
    # Runs every hour at minute 0; adjust as needed.
    - cron: "0 * * * *"
  workflow_dispatch:  # Allows you to run the workflow manually

# Ensure the workflow has permission to push changes
permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full history if needed

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Fetch Crypto Prices
        id: crypto
        run: |
          # Get BTC and ETH prices in USD from CoinGecko
          PRICES=$(curl -s "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum&vs_currencies=usd")
          echo "API output: $PRICES"
          PRICE_BTC=$(echo "$PRICES" | jq -r '.bitcoin.usd')
          PRICE_ETH=$(echo "$PRICES" | jq -r '.ethereum.usd')
          echo "Fetched Prices -> BTC: $PRICE_BTC, ETH: $PRICE_ETH"
          # Set these as outputs to use later
          echo "BTC=$PRICE_BTC" >> $GITHUB_ENV
          echo "ETH=$PRICE_ETH" >> $GITHUB_ENV

      - name: Update README with Crypto Prices
        run: |
          # Use Perl to replace the block between our comments
          perl -0777 -pi -e "s|<!-- CRYPTO_TICKER_START -->.*?<!-- CRYPTO_TICKER_END -->|<!-- CRYPTO_TICKER_START -->\n**BTC:** \$${BTC} **ETH:** \$${ETH}\n<!-- CRYPTO_TICKER_END -->|s" README.md
          echo "Updated README.md content:"
          cat README.md
        env:
          BTC: ${{ env.BTC }}
          ETH: ${{ env.ETH }}

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          # Only commit if changes exist
          git diff --cached --quiet || git commit -m "Update crypto prices"
          git push
